### ISSUE TITLE
Checklist para terminar

### ISSUE THREAD

**Issue by MrGaabriel** [PerfectDreams/DreamQuiz#1]
- [x] Colocar o tempo na bossbar (e fazer que tenha que responder mais rápido)
- [x] Fazer que os players sejam invisíveis para ficar mais desafiador
- [ ] Dar um mapinha comemorativo falando "Eu venci o quiz!"
- [x] Usar os sons da resource pack de "errou" e "acerto mizeravi" quando ganhar/perder
- [x] Apenas teletransportar os players após o som ter tocado
- [x] Tag especial para o(s) vencedor(es)

**Comment by MrGaabriel** [comment]
@MrPowerGamerBR tem que fazer a imagem do mapinha comemorativo
